import test from 'node:test';
import assert from 'node:assert/strict';
import {CASE_TYPES,planCaseStudy} from '../scripts/case-study-plan.mjs';
const p=(id='hey')=>({id,name:'Case',headline:'A tested scope',category:'Technology',status:'In development',role:'Designed with AI assistance',problem:'Context',intro:'Details',decision:'Decision',result:'Observed result',limitation:'Not production-ready',links:[{label:'Source',url:'https://github.com/example/source'}]});
const node=[['Observer','Reads semantic state','https://github.com/example/source']];
test('seven legacy project kinds mapped',()=>assert.deepEqual(['hey','personal-browser-operator','scale-governor','motion','skill-builder','copywriting','website-builder'].map(id=>planCaseStudy(p(id)).type),['engineering','engineering','ai-workflow','motion','ai-workflow','communication','web-experience']));
test('six locked Selected Work types represented',()=>assert.deepEqual(['tari-cookies','hey','waai-id','personal-browser-operator','sarafcare','motion'].map(id=>planCaseStudy(p(id)).type),['research-ux','engineering','creative-editorial','engineering','business-campaign','motion']));
test('legacy deep link anchors preserved',()=>assert.deepEqual(planCaseStudy(p(),node).sections.map(s=>s.id),['story','process','outcome','technical']));
test('engineering architecture explorer selected',()=>assert.equal(planCaseStudy(p(),node).sections[3].kind,'architecture'));
test('UX with nodes still uses source-only proof',()=>assert.equal(planCaseStudy(p('tari-cookies'),node).sections[3].kind,'sources'));
test('creative with links uses source-only proof',()=>assert.equal(planCaseStudy(p('waai-id')).sections[3].kind,'sources'));
test('no public source hides evidence tab',()=>{const x=p('sarafcare');x.links=[];assert.deepEqual(planCaseStudy(x).sections.map(s=>s.id),['story','process','outcome'])});
test('invalid javascript link rejected',()=>{const x=p();x.links=[{label:'bad',url:'javascript:alert(1)'}];assert.throws(()=>planCaseStudy(x),/UNSAFE_OR_MISSING_SOURCE_LINK/)});
test('credential URL rejected',()=>{const x=p();x.links=[{label:'bad',url:'https://u:p@example.com/'}];assert.throws(()=>planCaseStudy(x),/UNSAFE_OR_MISSING_SOURCE_LINK/)});
test('media injection blocked',()=>{const x=p();x.caseStudy={media:{src:'private'}};assert.throws(()=>planCaseStudy(x),/MEDIA_REQUIRES_SEPARATE_CLEARANCE/)});
test('unapproved kind rejected',()=>{const x=p();x.caseStudy={type:'guaranteed-return'};assert.throws(()=>planCaseStudy(x),/UNSUPPORTED_KIND/)});
test('eight supported types',()=>assert.equal(CASE_TYPES.length,8));
test('planner preserves legacy content input',()=>{const x=p('motion');const before=JSON.stringify(x);const v=planCaseStudy(x,node);assert.equal(JSON.stringify(x),before);assert.equal(v.outcome.limitation,x.limitation)});
test('missing contribution not fabricated',()=>{const x=p();delete x.role;assert.equal(planCaseStudy(x).contribution,'')});
test('no links allowed',()=>{const x=p();x.links=[];assert.equal(planCaseStudy(x).sources.length,0)});
test('unsafe node link rejected',()=>assert.throws(()=>planCaseStudy(p(),[['step','role','http://unsafe.example']]),/INVALID_ARCHITECTURE_NODE/));
test('non-string result rejected',()=>{const x=p();x.result=3;assert.throws(()=>planCaseStudy(x),/INVALID_FIELD_result/)});
test('contribution override preserved',()=>{const x=p();x.caseStudy={contribution:'Work and decisions'};assert.equal(planCaseStudy(x).contribution,'Work and decisions')});
test('private source absent does not create artificial proof',()=>{const x=p();x.links=[];assert.equal(planCaseStudy(x).noPublicSources,true)});
