/* ARS static site generator. Node.js 20+, no dependencies. All text comes from reviewed content JSON. */
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {loadV2ReleaseView} from '../v2/scripts/generator-bridge.mjs';
import {planEditorialGallery} from '../v2/scripts/gallery-plan.mjs';
import {planPublicWorkDisplay,renderPublicWorkDisplayCards} from '../v2/scripts/public-work-display.mjs';
import {planCaseStudy} from '../v2/scripts/case-study-plan.mjs';
import {resolveApprovedMedia} from '../v2/scripts/media-plan.mjs';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const fullCatalog=JSON.parse(readFileSync(resolve(root,'content/projects.json'),'utf8'));
const releaseView=loadV2ReleaseView({root,catalog:fullCatalog,manifestPath:process.env.ARS_V2_CANDIDATE_MANIFEST??null});
const items=releaseView.items;
const art=JSON.parse(readFileSync(resolve(root,'content/artwork.json'),'utf8'));
const arch=JSON.parse(readFileSync(resolve(root,'content/architecture.json'),'utf8'));
const mediaRegistry=JSON.parse(readFileSync(resolve(root,'v2/content/approved-media.json'),'utf8'));
const publicDisplay=JSON.parse(readFileSync(resolve(root,'v2/content/public-work-display.json'),'utf8'));
const homePortrait=resolveApprovedMedia(mediaRegistry,'ars-portrait','home');
const aboutPortrait=resolveApprovedMedia(mediaRegistry,'ars-portrait','about');
const motionMedia=resolveApprovedMedia(mediaRegistry,'motion-original-demo','motion-case');
const motionPoster=resolveApprovedMedia(mediaRegistry,'motion-original-poster','motion-case');
const galleryMotion=resolveApprovedMedia(mediaRegistry,'motion-original-demo','motion-gallery');
const galleryPoster=resolveApprovedMedia(mediaRegistry,'motion-original-poster','motion-gallery');
const motionPreview=resolveApprovedMedia(mediaRegistry,'motion-original-contact-sheet','motion-case');
const buildSite=(items, art, architecture) => {
 const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
 const host="https://arsafiqri-aybi.github.io";
 const header=(prefix="./",section=false)=>`<a class="skip" href="#main">Skip to content</a>`;
 const head=(title,desc,path="",prefix="./")=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><meta name="theme-color" content="#151719"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:type" content="website"><meta property="og:url" content="${host}/${path}"><meta property="og:image" content="${host}/social.svg"><link rel="canonical" href="${host}/${path}"><link rel="icon" href="${prefix}favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${prefix}fonts.css"><link rel="stylesheet" href="${prefix}assets/illustrations.css"><link rel="stylesheet" href="${prefix}styles.css?v=grid-detail-20"><script defer src="${prefix}app.js?v=grid-detail-20"></script></head>`;
 const artCaption=p=>["hey","personal-browser-operator"].includes(p.id)?"Source-derived system diagram · not a product screenshot":"Editorial illustration · not a product screenshot";
 const artEl=(p,extra="")=>`<div class="project-art tone-${esc(p.tone)} ${extra}" role="img" aria-label="${esc(artCaption(p))}">${art[p.id]??""}</div>`;
 const workHref=p=>`./work/${p.id}/`;
 const contact=`<div class="contact-simple"><h1>Let's talk about what you're building.</h1><p>Whether it's a digital experience, a creative direction, or a problem worth exploring, I'd be glad to hear what you have in mind.</p><div class="contact-actions"><a href="https://www.instagram.com/arsafiqri_ua/">Instagram</a><a href="https://github.com/arsafiqri-aybi">GitHub</a></div></div>`;
 const navNames=["Home","Work","Expertise","Approach","About","Connect"];
 const nav=navNames.map((n,i)=>`<button class="rail-choice" type="button" data-rail="${n.toLowerCase()}" aria-current="${i===0?"true":"false"}" tabindex="${i===0?"0":"-1"}">${n}</button>`).join("");
 const galleryPlan=planEditorialGallery(items,releaseView.selectedIds);
 const selected=galleryPlan.selected.map(entry=>items.find(p=>p.id===entry.id));
 const previewWork=selected[0]??items[0];
 const displayedWork=planPublicWorkDisplay(publicDisplay,items);
 const featuredCards=renderPublicWorkDisplayCards(displayedWork,items,art,esc,artEl,artCaption,{video:galleryMotion,poster:galleryPoster});
 const indexRows=galleryPlan.allWork.map(p=>`<a class="index-row" href="${workHref(p)}" data-gallery-project="${esc(p.id)}"><span class="index-title">${esc(p.name)}</span><span class="index-category">${esc(p.category)}</span><span class="index-status">${esc(p.status)}</span></a>`).join("");
 const previews=[
 `<article class="section-preview is-selected" data-preview="home"><div class="home-composition"><div class="identity-copy"><h1>Turning insight into <em>experiences that work.</em></h1><p>I connect business thinking, creative strategy, and technology to build thoughtful digital experiences and AI-connected systems.</p></div><figure class="side-artwork ars-portrait-stage"><img src="./${esc(homePortrait.path)}" width="${homePortrait.width}" height="${homePortrait.height}" alt="${esc(homePortrait.alt)}" fetchpriority="high" decoding="async"></figure></div></article>`,
 `<article class="section-preview" data-preview="work"><div class="work-composition"><div class="preview-copy"><h2><a class="preview-heading-link" href="#work" data-open="work" aria-label="Open work section">Ideas made <em>tangible.</em></a></h2><p>From research-led interfaces and creative strategy to AI-connected systems and code-driven motion.</p></div><a class="work-art-focus" href="${workHref(previewWork)}">${artEl(previewWork)}</a></div></article>`,
 `<article class="section-preview" data-preview="expertise"><div class="type-composition"><h2><a class="preview-heading-link" href="#expertise" data-open="expertise" aria-label="Open expertise section">Where thinking <em>meets making.</em></a></h2><div class="preview-capabilities"><p>Strategy &amp; Research</p><p>Creative &amp; Marketing</p><p>Digital Engineering</p><p>Motion &amp; Experience</p></div></div></article>`,
 `<article class="section-preview" data-preview="approach"><div class="type-composition"><h2><a class="preview-heading-link" href="#approach" data-open="approach" aria-label="Open approach section">Thoughtful by <em>design.</em></a></h2><p class="lead">Understand. Decide. Build. Verify.</p></div></article>`,
 `<article class="section-preview" data-preview="about"><div class="type-composition"><h2><a class="preview-heading-link" href="#about" data-open="about" aria-label="Open about section">Hi, I'm <em>Ars.</em></a></h2><p class="lead">I study Digital Business and explore where strategy, creative work, and digital technology meet.</p></div></article>`,
 `<article class="section-preview" data-preview="connect"><div class="type-composition"><h2><a class="preview-heading-link" href="#connect" data-open="connect" aria-label="Open connect section">Let's build <em>something meaningful.</em></a></h2><p class="lead">A place to talk about a digital experience, a creative direction, or a problem worth exploring.</p></div></article>`
 ].join("");
 const workPage=`<section class="page" id="work" data-page="work"><div class="page-inside"><a class="back-action" href="./" data-back>Back to explore</a><div class="page-heading"><h1>Different disciplines. <em>Shared intent.</em></h1><p>An exploration of business thinking, creative strategy, and technology through research-led experiences, independent projects, and documented experiments.</p></div>${displayedWork.length?`<div class="selected-work editorial-gallery">${featuredCards}</div>`:""}<div class="archive-section"><div class="archive-heading"><h2>All Work.</h2><p>A complete index of available projects.</p></div><div class="quiet-index">${indexRows}</div></div><div class="end-note"><p>Interested in how these systems were built?</p><a class="quiet-action" href="#expertise" data-open="expertise">Explore expertise</a></div></div></section>`;
 const expertisePage=`<section class="page" id="expertise" data-page="expertise"><div class="page-inside editorial-page"><a class="back-action" href="./" data-back>Back to explore</a><div class="page-heading"><h1>Where thinking <em>meets making.</em></h1><p>My work moves across four connected disciplines: understanding people and problems, shaping ideas, building digital systems, and exploring how experiences feel and behave.</p></div><div class="editorial-stack"><article class="capability"><div><h2>Strategy &amp; Research.</h2><p>I use customer questions, audience observations, and business context to understand what needs to change before deciding what to make.</p></div><div class="capability-note" aria-hidden="true"><span>Understand</span><span>Question</span><span>Decide</span></div></article><article class="capability"><div><h2>Creative &amp; Marketing.</h2><p>I shape messages, content, and campaign journeys, then use the response they receive to inform what comes next.</p></div><div class="capability-note" aria-hidden="true"><span>Message</span><span>Story</span><span>Response</span></div></article><article class="capability"><div><h2>Digital Engineering.</h2><p>I develop frontend experiences and AI-connected tools with attention to interaction, control, and the difference between an action and a verified result.</p><a class="text-destination" href="${workHref(items.find(p=>p.id==="hey"))}">Explore Hey by Ars</a></div><div class="capability-media">${artEl(items.find(p=>p.id==="hey"))}<small>Editorial illustration · system in development</small></div></article><article class="capability"><div><h2>Motion &amp; Experience.</h2><p>I explore how timing, form, and interaction can change the way information is seen and understood.</p><a class="text-destination" href="${workHref(items.find(p=>p.id==="motion"))}">Explore Motion Render Video</a></div><div class="capability-media">${artEl(items.find(p=>p.id==="motion"))}<small>Editorial illustration · original render in case study</small></div></article></div></div></section>`;
 const approachPage=`<section class="page" id="approach" data-page="approach"><div class="page-inside editorial-page"><a class="back-action" href="./" data-back>Back to explore</a><div class="page-heading"><h1>Understand. Decide. <em>Build. Verify.</em></h1><p>Different projects call for different methods. These four questions keep my work connected to the people, decisions, and evidence behind it.</p></div><div class="principles"><article><h2>Understand — What is actually unclear?</h2><p>Start with the people involved, the problem they face, and the information that is missing.</p></article><article><h2>Decide — Which choice makes the experience clearer?</h2><p>Choose the message, interaction, or journey that fits the problem rather than adding complexity by default.</p><a class="text-destination" href="${workHref(items.find(p=>p.id==="scale-governor"))}#process">Explore a decision · Scale &amp; Governor</a></article><article><h2>Build — How should the pieces work together?</h2><p>Turn decisions into tangible experiences, connecting the interface to the behavior behind it.</p><a class="text-destination" href="${workHref(items.find(p=>p.id==="hey"))}#process">Explore a system · Hey by Ars</a></article><article><h2>Verify — What does the evidence actually prove?</h2><p>Look at the result, state the limitations, and keep the next improvement grounded in what was observed.</p><a class="text-destination" href="${workHref(items.find(p=>p.id==="personal-browser-operator"))}#outcome">Explore a test · Personal Browser Operator</a></article></div></div></section>`;
 const aboutPage=`<section class="page" id="about" data-page="about"><div class="page-inside editorial-page"><a class="back-action" href="./" data-back>Back to explore</a><div class="page-heading"><h1>Arsafiqri <em>Ummati Aybi.</em></h1></div><div class="about-layout"><div class="about-story"><p class="lead">I'm an undergraduate Digital Business student at Universitas Cakrawala, exploring the intersection of business strategy, creative work, and digital technology.</p><p>My experience spans understanding customers, shaping content and campaigns, contributing to collaborative UX projects, and developing personal digital systems with AI assistance.</p><p>What connects these experiences is my interest in the decisions behind the work: what people need, why an approach makes sense, and how to understand whether an idea has become useful.</p><p>I see strategy and implementation as connected parts of the same process. I want the thinking behind an idea to become visible in the experience people actually use.</p><div class="about-actions"><a class="text-destination" href="#work" data-open="work">Explore work</a><a class="text-destination" href="https://github.com/arsafiqri-aybi">GitHub</a></div></div><figure class="about-portrait"><img src="./${esc(aboutPortrait.path)}" width="${aboutPortrait.width}" height="${aboutPortrait.height}" alt="${esc(aboutPortrait.alt)}" loading="lazy" decoding="async"><figcaption>Arsafiqri Ummati Aybi · ARS</figcaption></figure></div></div></section>`;
 const connectPage=`<section class="page" id="connect" data-page="connect"><div class="page-inside"><a class="back-action" href="./" data-back>Back to explore</a>${contact}</div></section>`;
 const footer=``;
 const home=head("ARS — Digital Builder × Business Strategist","Arsafiqri Ummati Aybi. Digital Builder × Business Strategist. Connecting business thinking, creative strategy, and technology.")+`<body class="home-site">${header()}<noscript><nav class="static-nav" aria-label="Portfolio sections">${navNames.map(n=>`<a href="#${n.toLowerCase()}">${n}</a>`).join("")}</nav></noscript><main id="main"><section class="explorer" id="home" data-explorer aria-label="Explore ARS portfolio"><div class="explore-frame"><div class="explore-layout"><nav class="section-rail" aria-label="Portfolio sections"><div class="rail-window"><div class="rail-list"><span class="rail-leading-space" aria-hidden="true"></span>${nav}</div></div></nav><div class="preview-stage">${previews}</div></div></div></section>${workPage}${expertisePage}${approachPage}${aboutPage}${connectPage}</main>${footer}</body></html>`;
 const casePage=(p,i)=>{
  const plan=planCaseStudy(p,architecture[p.id]??[]);
  const next=items.find(x=>x.id===galleryPlan.nextWork[p.id]);
  const first=plan.sources[0]??null;
  const sources=label=>plan.sources.length?`<div class="source-list"><span>${esc(label)}</span>${plan.sources.map(l=>`<a href="${esc(l.url)}" class="source-ref">${esc(l.label)}</a>`).join("")}</div>`:"";
  const nodesHtml=plan.architecture.map((n,j)=>`<button class="architecture-node" type="button" data-node="${j}" data-role="${esc(n[1])}" data-source="${esc(n[2])}" aria-pressed="${j===0?"true":"false"}">${esc(n[0])}</button>`).join('<span class="architecture-flow" aria-hidden="true">→</span>');
  const sourceMedia=Boolean(art[p.id]);
  const heroMedia=sourceMedia?`<div class="showcase-art">${artEl(p)}</div><span class="art-disclaimer">${esc(artCaption(p))}</span>`:"";
  const evidence=p.id==="motion"?`<figure class="evidence-real"><div class="motion-player" data-motion-player><video controls preload="none" playsinline poster="${esc(motionPoster.dataUrl)}" aria-label="Original six-second code-rendered motion demonstration"><source src="${esc(motionMedia.url)}" type="video/mp4"><track kind="captions" src="../../assets/motion-captions.vtt" srclang="en" label="English">Video playback unavailable.</video><button class="motion-play-cover" type="button" data-motion-play aria-label="Play original six-second motion video"><span class="motion-direct-frame" aria-hidden="true"><img src="${esc(motionPoster.dataUrl)}" width="640" height="360" alt="" loading="lazy" decoding="async"></span><span class="motion-play-label" aria-hidden="true">Play film <span>▶</span></span></button></div><span class="motion-play-error" role="status" data-motion-error></span><figcaption>Original six-second code-rendered study · Poster extracted directly from frame 179. <a href="../../${esc(motionPreview.path)}">View sampled frames</a>.<details class="film-description"><summary>Film description</summary><p>A red circle follows a curved line, changes into a square, and settles at the endpoint. Labels introduce Form, Time, and Sound, accompanied by four sound cues. The original heading translates as “Movement becomes visible.”</p></details></figcaption></figure>`:sourceMedia?`<figure class="evidence-editorial">${artEl(p)}<figcaption>${esc(artCaption(p))} · not a verified result.</figcaption></figure>`:"";
  const nav=plan.sections.map(s=>`<a href="#${esc(s.id)}"${s.id==="story"?' aria-current="true"':""}>${esc(s.nav)}</a>`).join("");
  const aside=plan.contribution||p.status?`<aside class="quick-aside">${plan.contribution?`<div><small>My contribution</small><p>${esc(plan.contribution)}</p></div>`:""}${p.status?`<div><small>Project status</small><p>${esc(p.status)}</p></div>`:""}</aside>`:"";
  const story=`<section class="reading-section story-section" id="story"><div class="editorial-width"><span class="overline">Context &amp; Contribution</span><h2>${esc(plan.sections[0].heading)}</h2><div class="context-grid"><div class="reading-copy">${plan.context.problem?`<p>${esc(plan.context.problem)}</p>`:""}${plan.context.intro?`<p>${esc(plan.context.intro)}</p>`:""}</div>${aside}</div></div></section>`;
  const process=`<section class="reading-section process-section" id="process"><div class="editorial-width"><span class="overline">Decisions &amp; Process</span><h2>${esc(plan.sections[1].heading)}</h2><div class="evidence-pair${evidence?"":" case-text-evidence"}"><div class="reading-copy"><h3>${esc(plan.decision.headline)}</h3>${plan.decision.text?`<p>${esc(plan.decision.text)}</p>`:""}</div>${evidence}</div></div></section>`;
  const outcome=`<section class="reading-section outcome-section" id="outcome"><div class="editorial-width"><span class="overline">Outcome &amp; Limitations</span><h2>${esc(plan.sections[2].heading)}</h2>${plan.outcome.result?`<p class="reading-lead">${esc(plan.outcome.result)}</p>`:""}<div class="outcome-columns"><div><h3>Current scope</h3><p>${esc(plan.outcome.status)}</p></div><div><h3>What remains limited</h3><p>${esc(plan.outcome.limitation)}</p></div></div>${plan.sections.length===3?sources("Available source references"):""}</div></section>`;
  const evidenceSection=plan.sections.some(s=>s.id==="technical")?`<section class="reading-section technical-section" id="technical"><div class="editorial-width"><span class="overline">Supporting Evidence</span><h2>${esc(plan.sections.find(s=>s.id==="technical").heading)}</h2>${plan.architecture.length?`<div class="architecture-explorer"><div class="architecture-canvas" role="group" aria-label="Documented system components">${nodesHtml}</div><div class="architecture-info" aria-live="polite"><h3 data-node-name>${esc(plan.architecture[0][0])}</h3><p data-node-role>${esc(plan.architecture[0][1])}</p><a data-node-link class="text-destination" href="${esc(plan.architecture[0][2])}">Inspect source</a></div></div>`:""}${sources("Original documentation")}</div></section>`:"";
  const nextBlock=next?`<div class="next-work"><span>Continue exploring</span><a href="../${esc(next.id)}/">${esc(next.name)}</a><a href="../../#work" data-return-to-work>All Work</a></div>`:`<div class="next-work"><a href="../../#work" data-return-to-work>All Work</a></div>`;
  return head(`${p.name} — ARS`,p.summary,`work/${p.id}/`,"../../")+`<body class="project-page case-type-${esc(plan.type)}" data-case="${esc(p.id)}">${header("../../")}<main id="main"><section class="showcase"><div class="showcase-inside"><a class="back-action" href="../../#work" data-return-to-work>Back to All Work</a><div class="showcase-title"><span class="overline">${esc(plan.hero.category)} · ${esc(plan.hero.status)}</span><h1>${esc(p.name)}<span>.</span></h1><p>${esc(plan.hero.headline)}</p></div>${heroMedia}<div class="hero-sources">${first?`<a href="${esc(first.url)}">${esc(first.label)}</a>`:""}<span>${esc(p.year??"")} · ${esc(plan.hero.status)}</span></div></div></section><div class="reader" data-reader><nav class="story-nav" aria-label="Case study sections">${nav}</nav>${story}${process}${outcome}${evidenceSection}${nextBlock}</div></main>${footer.replace('href="#home"','href="../../#home"')}</body></html>`.replaceAll('src="./assets/core.svg"','src="../../assets/core.svg"');
 };
 const files=[{path:"index.html",content:home},{path:"404.html",content:head("Page not found — ARS","Return to ARS portfolio.","404.html","/")+`<body class="project-page">${header("/")}<main class="not-found" id="main"><h1>This page isn't here.</h1><p>Explore the available work instead.</p><a class="quiet-action" href="/#work">Explore work</a></main>${footer.replace('href="#home"','href="/#home"')}</body></html>`},{path:"sitemap.xml",content:`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`+["",...items.map(p=>`work/${p.id}/`)].map(x=>`<url><loc>${host}/${x}</loc></url>`).join("")+"</urlset>"},{path:"robots.txt",content:`User-agent: *\nAllow: /\nDisallow: /docs/\nDisallow: /content/\nDisallow: /scripts/\nSitemap: ${host}/sitemap.xml\n`}];
 items.forEach((p,i)=>files.push({path:`work/${p.id}/index.html`,content:casePage(p,i)}));
 return files;
};
for(const f of buildSite(items,art,arch)){const path=resolve(root,f.path);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,f.content);}
console.log('ARS generated: homepage, '+items.length+' case studies, 404, sitemap and robots.');
