/* Reproducible local lab measurements; no field CWV or universal smoothness claim. */
const fs=require('fs'),path=require('path'),http=require('http'),zlib=require('zlib'),cp=require('child_process');
const {chromium}=require('playwright');const root=path.resolve(__dirname,'..');
const baseline=path.resolve(root,'..','qa-baseline');fs.mkdirSync(baseline,{recursive:true});
for(const f of ['index.html','styles.css','fonts.css','app.js','favicon.svg'])fs.writeFileSync(path.join(baseline,f),cp.execFileSync('git',['show',`a8b002eba7b540c9600ac34d9b7d405761786c46:${f}`],{cwd:root}));
const server=http.createServer((req,res)=>{const old=req.url.startsWith('/baseline/');let f=path.join(old?baseline:root,decodeURIComponent(req.url.replace(/^\/baseline\//,'/').split('?')[0]));if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',({'html':'text/html','css':'text/css','js':'text/javascript','svg':'image/svg+xml'})[f.split('.').pop()]||'text/plain');res.setHeader('Content-Encoding','gzip');res.end(zlib.gzipSync(fs.readFileSync(f)));});
async function main(){await new Promise(r=>server.listen(4173,r));const browser=await chromium.launch({headless:true,executablePath:process.env.QA_CHROMIUM,args:['--no-sandbox','--no-zygote','--disable-dev-shm-usage','--disable-gpu']});
 const report={date:'2026-10-08',environment:{browser:await browser.version(),viewport:{width:390,height:844},dpr:1,cpu_throttle:4,network:{latency_ms:150,download_bytes_per_sec:200000,upload_bytes_per_sec:93750},server:'local Node HTTP with gzip',cache:'disabled / new context each run',scope:'Lab only; baseline and candidate have different content and visuals. No causal speed improvement or field INP claim.'},runs:[],bytes:{},motion:null};
 for(const variant of ['baseline','candidate'])for(let run=1;run<=3;run++){
  const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,reducedMotion:'no-preference'});const page=await context.newPage();const cdp=await context.newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:200000,uploadThroughput:93750});await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});
  await page.addInitScript(()=>{window.lab={lcp:[],shifts:[],tasks:[],events:[]};for(const [name,type]of [['lcp','largest-contentful-paint'],['shifts','layout-shift'],['tasks','longtask'],['events','event']]){try{new PerformanceObserver(l=>{for(const e of l.getEntries())window.lab[name].push(name==='shifts'?{start:e.startTime,value:e.value,recent:e.hadRecentInput}:{start:e.startTime,duration:e.duration,size:e.size||0,interactionId:e.interactionId||0})}).observe({type,buffered:true,durationThreshold:16})}catch{}}});
  await page.goto(`http://127.0.0.1:4173/${variant==='baseline'?'baseline/':''}`,{waitUntil:'networkidle'});await page.waitForTimeout(1200);
  const metrics=await page.evaluate(()=>{const d=window.lab;let cls=0,sum=0,start=0,last=0;for(const e of d.shifts.filter(s=>!s.recent)){if(e.start-last>1000||e.start-start>5000){sum=0;start=e.start;}sum+=e.value;cls=Math.max(cls,sum);last=e.start;}return{lcp_ms:d.lcp.at(-1)?.start??null,cls,long_tasks:d.tasks.length,max_long_task_ms:Math.max(0,...d.tasks.map(x=>x.duration)),resources:performance.getEntriesByType('resource').map(r=>({name:new URL(r.name).pathname,transfer:r.transferSize,encoded:r.encodedBodySize,decoded:r.decodedBodySize})),raw:d}});
  report.runs.push({variant,run,...metrics});console.log(variant,run,JSON.stringify({lcp_ms:metrics.lcp_ms,cls:metrics.cls,long_tasks:metrics.long_tasks}));await context.close();
 }
 for(const f of ['index.html','styles.css','app.js','fonts.css','assets/core.svg']){const b=fs.readFileSync(path.join(root,f));report.bytes[f]={raw:b.length,gzip:zlib.gzipSync(b).length};}
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'no-preference'});const p=await context.newPage();await p.goto('http://127.0.0.1:4173/');await p.waitForTimeout(1200);const cdp=await context.newCDPSession(p);await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});
 const motion=await p.evaluate(()=>new Promise(resolve=>{const intervals=[];let last,frames=0;const step=t=>{if(last)intervals.push(t-last);last=t;const progress=(frames%120)/120;scrollTo(0,Math.sin(progress*Math.PI)*1400);if(frames%15===0)document.querySelectorAll('.work-choice')[(frames/15)%6|0].click();frames++;if(frames<180)requestAnimationFrame(step);else resolve(intervals);};requestAnimationFrame(step);}));
 const sorted=[...motion].sort((a,b)=>a-b);report.motion={scenario:'180 rAF callbacks with forward/reverse native scroll and 12 rapid work changes; 1440×1000; 4× CPU; unthrottled local network',intervals_ms:motion,median_ms:sorted[Math.floor(sorted.length*.5)],p95_ms:sorted[Math.floor(sorted.length*.95)],over_33_ms:motion.filter(v=>v>33).length,scope:'rAF scheduling intervals, not a full compositor/presentation frame trace; software headless browser, not a physical phone'};
 const vt=[];p.on('console',msg=>{if(msg.text().startsWith('ARS_VT'))vt.push(msg.text())});await p.addInitScript(()=>addEventListener('pagereveal',event=>{if(event.viewTransition)console.log('ARS_VT cross-document active')}));await p.goto('http://127.0.0.1:4173/');await p.locator('[data-project="hey"]').click();await p.locator('#preview-hey .project-art').click();await p.waitForURL('**/work/hey/');await p.waitForTimeout(800);report.native_transition={observed:vt.length>0,events:vt};
 await context.close();await browser.close();server.close();fs.writeFileSync(path.join(root,'docs/performance-lab.json'),JSON.stringify(report,null,2)+'\n');console.log('MOTION',JSON.stringify({...report.motion,intervals_ms:undefined}));console.log('NATIVE_TRANSITION',report.native_transition);
}
main().catch(error=>{console.error(error);server.close();process.exit(1)});
